App.tsx
android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/whatyoulookingapp/MainApplication.kt
android/build.gradle
android/settings.gradle
package-lock.json
package.json

build: set up ViroReact

---

README.md

Delete template README content and replace with
project-specific content.

docs: start README

---

App.tsx
android/app/src/main/java/com/whatyoulookingapp/MainActivity.kt
package-lock.json
package.json

Set up react navigation settings and configure
App.tsx to render components with navigation stack

build: install react-navigation

---

.eslintrc.js
App.tsx
android/app/src/main/AndroidManifest.xml
package-lock.json
package.json
src/modules/permissions.ts

Ask for location permission.
Retrieve geo location if permission given.

feat: get user location on app load

---

App.tsx
package-lock.json
src/components/ErrorScreen.tsx
src/components/LocationDeniedError.tsx

Renders an error screen when user doesn't give location permission.

Location permission denied

---

src/components/HomeScreen.tsx
src/components/PointMarker.tsx
test-data.json

Create HomeScreenARScene and render a PointMarker for each location in testData

Point marker

---

package-lock.json
package.json
src/components/HomeScreen.tsx
src/types/react-native-compass-heading.d.ts

HomeScreen now accesses phone's compass heading.

Compass heading

---

App.tsx
src/components/PlaceDetails.tsx
src/types/route.d.ts
test-data-place.json

Render details about the place from the API
Creates screen on route PlaceDetails
Takes parameter of PlaceData

feat: create PlaceDetails component

---

App.tsx
src/components/HomeScreen.tsx
src/components/PointMarker.tsx
src/modules/apis.ts

Display icons above nearby museums.
Move userLocation to HomeScreen component.
Combine userLocation, compassHeading and API call.

feat: create working prototype

---

src/modules/apis.ts

This ensures api errors don't crash the app, instead the error is logged and the function returns undefined.

refactor: put all response handling logic inside try blocks in api functions

---

src/components/PlaceDetails.tsx
src/components/StyledButton.tsx

Added styling to PlaceDetails
Created StyledButton component

Styling place details

---

App.tsx
src/components/PlaceDetails.tsx
src/components/PointMarker.tsx
src/modules/apis.ts
src/types/route.d.ts

Can click icon to go to details page
Can click back button to go to the AR screen
Removed header on details screen to prevent app crashing

Navigation from icon to details page and back

---

App.tsx
src/components/PlaceDetails.tsx
src/components/PointMarker.tsx
src/modules/apis.ts

Fix error loading data when no overview exists.
Fix app not loading home screen on start.

fix: fix errors regarding PlaceDetails component

---

App.tsx
src/components/HomeButton.tsx
src/components/PlaceCard.tsx
src/components/PlaceDetails.tsx
src/components/PlacesList.tsx
src/types/route.d.ts

Component for Places List
Component for Places Card
Component for Home navigation
Navigation routes enabled for going from list of places to the detail page and back again.

Create places list component

---

src/components/FilterBy.tsx
src/components/Menu.tsx

Add dropdown menu with options for types of places to show and add a select all and deselect all

feat: make burger menu with select types

---

package-lock.json
package.json
src/components/PlaceDetails.tsx
src/components/PlacesList.tsx

Added local storage for place details
Added ability to save to favourites list, view the list and clear the list

Local storage

---

src/components/Menu.tsx
src/components/NavButton.tsx
src/types/route.d.ts

Create reusable NavButton component.
Add NavButton to Menu which navigates to PlacesList.

feat: add button to nav menu to navigate to favourites

---

src/components/PlaceCard.tsx
src/components/PlacesList.tsx

Added functionality to 'Remove' button 
Pressing 'Remove' button deletes card from the places list

feat: delete list item

---

App.tsx
src/components/Filter.tsx
src/components/HomeScreen.tsx
src/components/Menu.tsx
src/components/NavButton.tsx

Remove chips and amend other styling options in
multi select

feat: amend sectioned multi select

---

env.d.ts
src/modules/apis.ts
src/types/route.d.ts

getNearbyEvents - finds nearest 5 events based on the user's latitude and longitude
getEventDetails - fetches event details based on event ID

feat: create event apis

---

App.tsx
src/components/EventDetails.tsx
src/modules/apis.ts
src/types/route.d.ts

Created event details page including event name, image, address, start date/time
Updated event APIs to display additional information
Added map view to event details page

feat: create event details page

---

src/components/EmbeddedMap.tsx
src/components/MapPage.tsx
src/types/route.d.ts

Make map markers navigate to PlaceDetails on press in map component.

feat: display different icons for each POI type in map component

---

src/components/HomeScreen.tsx

feat: render loading modal until loaded and

---

src/components/EmbeddedMap.tsx

Remove title 'you' from current location and adjust default zoom level.

feat: refine embedded app
